### ISSUE TITLE
might be a tiny mistake in LSTM code

### ISSUE THREAD

**Issue by skyblueee** [cristianleoo/models-from-scratch-python#1]
Hi, your article _The Math Behind LSTM_ led me here, and I appreciate your work very much.

While I repeat the process, I think there might be a tiny mistake in the code:

in LSTM/TimeSeriesDataset/load_data function:

```
df = df[(df['Date'] >= self.start_date) & (df['Date'] <= self.end_date)]   # A
df = df.sort_index()  # B
df = df.loc[self.start_date:self.end_date]  # C
```

Line C filters thousands of rows to only 15 rows, which is too small for the dataset. I think maybe you intended to make the same filtering as line A but coded wrong (because loc() use index by default)?

And maybe line B is also unnecessary but harmless?

Thanks for your amazing work again!

**Comment by cristianleoo** [comment]
Hi @skyblueee, thank you so much for pointing out the issue. I am removing line C from the code. As for line B, in this code is a bit redundant, as the dataset is already ordered. However, it would be nice to leave it there for scalability.
